# ============================================
# 592Meal Docker Compose 配置
# ============================================
# 用於正式環境與測試環境部署
# 開發環境請使用 Laragon
# ============================================

services:
  # ==========================================
  # Nginx Web Server
  # ==========================================
  nginx:
    image: nginx:1.25-alpine
    container_name: 592meal_nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/ssl.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
      - 592meal_storage:/var/www/html/www/storage/app/public
    depends_on:
      - php
    networks:
      - 592meal

  # ==========================================
  # PHP-FPM 8.4
  # ==========================================
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: 592meal_php
    restart: unless-stopped
    working_dir: /var/www/html/www
    # user: "root"                  <--- 刪除這一行
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - 592meal_storage:/var/www/html/www/storage/app/public
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_MAX_FILESIZE=20M
      - PHP_POST_MAX_SIZE=20M
    depends_on:
      - postgres
      - redis
    networks:
      - 592meal

  # ==========================================
  # PostgreSQL 18
  # ==========================================
  postgres:
    image: postgres:18-alpine
    container_name: 592meal_postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-592meal_prod}
      POSTGRES_USER: ${DB_USERNAME:-592meal}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - 592meal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-592meal}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # Redis 7.0
  # ==========================================
  redis:
    image: redis:7-alpine
    container_name: 592meal_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes --requirepass password
    volumes:
      - redis_data:/data
    networks:
      - 592meal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # ==========================================
  # Laravel Reverb (WebSocket)
  # ==========================================
  reverb:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: 592meal_reverb
    restart: unless-stopped
    working_dir: /var/www/html/www
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "${REVERB_PORT:-8080}:8080"
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis
    networks:
      - 592meal
    environment:
      - REVERB_HOST=0.0.0.0
      - REVERB_PORT=8080

  # ==========================================
  # Queue Worker (Supervisor)
  # ==========================================
  queue:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: 592meal_queue
    restart: unless-stopped
    working_dir: /var/www/html/www
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./:/var/www/html
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - postgres
      - redis
    networks:
      - 592meal

  # ==========================================
  # Scheduler (Cron)
  # ==========================================
  scheduler:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: 592meal_scheduler
    restart: unless-stopped
    working_dir: /var/www/html/www
    command: >
      sh -c "while true; do
        php artisan schedule:run --verbose --no-interaction &
        sleep 60
      done"
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - 592meal

# ==========================================
# Networks
# ==========================================
networks:
  592meal:
    driver: bridge

# ==========================================
# Volumes
# ==========================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local
  592meal_storage:
    driver: local
